# Generated by Django 2.1.2 on 2018-10-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='alcohol',
            field=models.FloatField(),
        ),
    ]
