# Generated by Django 2.1.2 on 2018-11-03 09:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181022_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('alcohol', models.IntegerField()),
                ('steps', models.IntegerField()),
                ('pressure', models.IntegerField()),
            ],
        ),
    ]
