# Generated by Django 2.1.2 on 2018-11-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('steps', models.PositiveIntegerField(default=0)),
                ('pulse', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Drinking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('alcohol', models.FloatField(default=0.0)),
            ],
        ),
    ]
