# Generated by Django 2.1.2 on 2018-11-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181104_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='user',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='drinking',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
